/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/{tenant_id}/credentials": {
    /**
     * List Credentials
     * @description Get a list of webauthn credentials for a user
     */
    get: operations["get-credentials"];
  };
  "/{tenant_id}/credentials/{credential_id}": {
    /**
     * Remove Credential
     * @description Endpoint for removing a webauthn credential
     */
    delete: operations["delete-credentials-credentialId"];
    /**
     * Update Credential
     * @description Endpoint for updating a webauthn credential
     */
    patch: operations["patch-credentials-credentialId"];
  };
  "/{tenant_id}/registration/initialize": {
    /**
     * Start Passkey Registration
     * @description Initialize a registration for webauthn credentials
     */
    post: operations["post-registration-initialize"];
  };
  "/{tenant_id}/registration/finalize": {
    /**
     * Finish Passkey Registration
     * @description Finish credential registration process
     */
    post: operations["post-registration-finalize"];
  };
  "/{tenant_id}/login/initialize": {
    /**
     * Start Login
     * @description Initialize a login flow for passkeys
     */
    post: operations["post-login-initialize"];
  };
  "/{tenant_id}/login/finalize": {
    /**
     * Finish Login
     * @description Finalize the login operation
     */
    post: operations["post-login-finalize"];
  };
  "/{tenant_id}/.well-known/jwks.json": {
    /**
     * Well-known JWKS
     * @description Endpoint for fetching JWKS
     */
    get: operations["get-.well-known-jwks.json"];
  };
  "/{tenant_id}/transaction/initialize": {
    /**
     * Initialize a transaction
     * @description Initializes a new transaction for an existing user
     */
    post: operations["post-tenant_id-transaction-initialize"];
  };
  "/{tenant_id}/transaction/finalize": {
    /**
     * Finalize transaction
     * @description Finalize a transaction
     */
    post: operations["post-tenant_id-transaction-finalize"];
  };
  "/{tenant_id}/mfa/registration/initialize": {
    /**
     * Start MFA Registration
     * @description Initialize a registration for mfa credentials
     */
    post: operations["post-mfa-registration-initialize"];
  };
  "/{tenant_id}/mfa/registration/finalize": {
    /**
     * Finish MFA Registration
     * @description Finish credential registration process
     */
    post: operations["post-mfa-registration-finalize"];
  };
  "/{tenant_id}/mfa/login/initialize": {
    /**
     * Start MFA Login
     * @description Initialize a login flow for MFA
     */
    post: operations["post-mfa-login-initialize"];
  };
  "/{tenant_id}/mfa/login/finalize": {
    /**
     * Finish MFA Login
     * @description Finalize the login operation
     */
    post: operations["post-mfa-login-finalize"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** public-key-credential */
    "public-key-credential": components["schemas"]["credential"] & ({
      rawId: string;
      /** @enum {string} */
      authenticatorAttachment?: "cross-platform" | "platform" | null;
    });
    /** credential */
    credential: {
      id: string;
      /** @enum {unknown} */
      type: "public-key";
    };
    /** authenticator-attestation-response */
    "authenticator-attestation-response": components["schemas"]["authenticator-response"] & {
      attestationObject: string;
      transports?: string[];
    };
    /** authenticator-response */
    "authenticator-response": {
      clientDataJSON: string;
    };
    /** autenticator-assertion-response */
    "autenticator-assertion-response": components["schemas"]["authenticator-response"] & {
      authenticatorData: string;
      signature: string;
      userHandle?: Record<string, never>;
    };
    /** relying-party-entity */
    "relying-party-entity": {
      id?: string;
    } & components["schemas"]["credential-entity"];
    /** credential-entity */
    "credential-entity": {
      name: string;
    };
    /** public-key-user */
    "public-key-user": {
      id: string;
      displayName: string;
      name: string;
    };
    /** credential-parameter-entity */
    "credential-parameter-entity": {
      /** @enum {unknown} */
      type: "public-key";
      /** Format: int32 */
      alg: number;
    };
    /** credential-descriptor-entity */
    "credential-descriptor-entity": {
      /** @enum {unknown} */
      type: "public-key";
      id: string;
      transports?: ("ble" | "hybrid" | "internal" | "nfc" | "usb")[];
    };
    /** authentication-selection-entity */
    "authentication-selection-entity": {
      /** @enum {string} */
      authenticatorAttachement?: "cross-platform" | "platform";
      /** @default false */
      requireResidentKey?: boolean;
      /** @enum {string} */
      residentKey?: "discouraged" | "preferred" | "required";
      /** @enum {string} */
      userVerification?: "discouraged" | "preferred" | "required";
    };
  };
  responses: {
    /** @description Example response */
    "get-credentials": {
      content: {
        "application/json": {
            id: string;
            name?: string;
            public_key: string;
            attestation_type: string;
            /** Format: uuid */
            aaguid: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            created_at: string;
            transports: string[];
            /** @default false */
            backup_eligible: boolean;
            /** @default false */
            backup_state: boolean;
            /** @default false */
            is_mfa: boolean;
          }[];
      };
    };
    /** @description Error Response with detailed information */
    error: {
      content: {
        "application/json": {
          /**
           * @example [
           *   "explanatory title"
           * ]
           */
          title?: string;
          /**
           * @example [
           *   "Information which helps resolving the problem"
           * ]
           */
          details?: string;
          status?: number;
        };
      };
    };
    /** @description Example response */
    "post-registration-initialize": {
      content: {
        "application/json": {
          publicKey: {
            rp: components["schemas"]["relying-party-entity"];
            user: components["schemas"]["public-key-user"];
            challenge: string;
            pubKeyCredParams: components["schemas"]["credential-parameter-entity"][];
            timeout?: number;
            excludeCredentials?: components["schemas"]["credential-descriptor-entity"][];
            authenticatorSelection?: components["schemas"]["authentication-selection-entity"];
            /** @enum {string} */
            attestation?: "direct" | "enterprise" | "indirect" | "none";
            extensions?: {
              appid?: string;
              appidExclude?: string;
              credProps?: boolean;
            };
          };
        };
      };
    };
    /** @description Example response */
    "post-login-initialize": {
      content: {
        "application/json": {
          publicKey?: {
            challenge: string;
            timeout?: number;
            rpId?: string;
            allowCredentials?: components["schemas"]["credential-descriptor-entity"][];
            /** @enum {string} */
            userVerification?: "discouraged" | "preferred" | "required";
            extensions?: {
              appid?: boolean;
              appidExclude?: boolean;
              credProps?: {
                rk?: boolean;
              };
            };
          };
          /** @enum {string} */
          mediation?: "optional" | "required" | "silent";
        };
      };
    };
    /** @description Example response */
    jwks: {
      content: {
        "application/json": {
          keys?: {
              /**
               * @example [
               *   "RS256"
               * ]
               */
              alg?: string;
              /**
               * @example [
               *   "AAAA"
               * ]
               */
              e?: string;
              /**
               * Format: uuid
               * @example [
               *   "483b2499-1ed7-4325-94e3-97e8118ceee9"
               * ]
               */
              kid?: string;
              /**
               * @example [
               *   "RSA"
               * ]
               */
              kty?: string;
              n?: string;
              /**
               * @example [
               *   "sig"
               * ]
               */
              use?: string;
            }[];
        };
      };
    };
    /** @description Example response */
    token: {
      content: {
        "application/json": {
          token?: string;
        };
      };
    };
  };
  parameters: {
    /** @description representational id of the user */
    user_id: string;
    /** @description UUID of the credential */
    credential_id: string;
    /** @description UUID of the tenant */
    tenant_id: string;
    /** @description Secret API key */
    "X-API-KEY": string;
  };
  requestBodies: {
    "patch-credential"?: {
      content: {
        "application/json": {
          name: string;
        };
      };
    };
    "post-registration-initialize"?: {
      content: {
        "application/json": {
          user_id: string;
          username: string;
          icon?: string;
          display_name?: string;
        };
      };
    };
    "post-registration-finalize"?: {
      content: {
        "application/json": components["schemas"]["public-key-credential"] & {
          response: components["schemas"]["authenticator-attestation-response"];
          transports?: string[];
        };
      };
    };
    "post-login-finalize"?: {
      content: {
        "application/json": components["schemas"]["public-key-credential"] & {
          response: components["schemas"]["autenticator-assertion-response"];
          clientExtensionResults: {
            appid?: boolean;
            appidExclude?: boolean;
            credProps?: {
              rk?: boolean;
            };
          };
        };
      };
    };
    "post-transaction-initialize"?: {
      content: {
        "application/json": {
          user_id: string;
          transaction_id: string;
          transaction_data: Record<string, never>;
        };
      };
    };
    /** @description Body for login/initialize */
    "post-login-initialize"?: {
      content: {
        "application/json": {
          /** @description optional - when provided the API Key needs to be sent to the server too. */
          user_id?: string;
        };
      };
    };
    "post-mfa-login-initialize"?: {
      content: {
        "application/json": {
          user_id: string;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List Credentials
   * @description Get a list of webauthn credentials for a user
   */
  "get-credentials": {
    parameters: {
      query: {
        user_id: components["parameters"]["user_id"];
      };
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody?: {
      content: {
        "*/*": never;
      };
    };
    responses: {
      200: components["responses"]["get-credentials"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Remove Credential
   * @description Endpoint for removing a webauthn credential
   */
  "delete-credentials-credentialId": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        credential_id: components["parameters"]["credential_id"];
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Update Credential
   * @description Endpoint for updating a webauthn credential
   */
  "patch-credentials-credentialId": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        credential_id: components["parameters"]["credential_id"];
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["patch-credential"];
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Start Passkey Registration
   * @description Initialize a registration for webauthn credentials
   */
  "post-registration-initialize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-registration-initialize"];
    responses: {
      200: components["responses"]["post-registration-initialize"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Finish Passkey Registration
   * @description Finish credential registration process
   */
  "post-registration-finalize": {
    parameters: {
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-registration-finalize"];
    responses: {
      200: components["responses"]["token"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Start Login
   * @description Initialize a login flow for passkeys
   */
  "post-login-initialize": {
    parameters: {
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-login-initialize"];
    responses: {
      200: components["responses"]["post-login-initialize"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Finish Login
   * @description Finalize the login operation
   */
  "post-login-finalize": {
    parameters: {
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-login-finalize"];
    responses: {
      200: components["responses"]["token"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Well-known JWKS
   * @description Endpoint for fetching JWKS
   */
  "get-.well-known-jwks.json": {
    parameters: {
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    responses: {
      200: components["responses"]["jwks"];
    };
  };
  /**
   * Initialize a transaction
   * @description Initializes a new transaction for an existing user
   */
  "post-tenant_id-transaction-initialize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-transaction-initialize"];
    responses: {
      200: components["responses"]["post-login-initialize"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Finalize transaction
   * @description Finalize a transaction
   */
  "post-tenant_id-transaction-finalize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        tenant_id: components["parameters"]["tenant_id"];
      };
    };
    requestBody: components["requestBodies"]["post-login-finalize"];
    responses: {
      200: components["responses"]["token"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Start MFA Registration
   * @description Initialize a registration for mfa credentials
   */
  "post-mfa-registration-initialize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        /** @description Tenant ID */
        tenant_id: string;
      };
    };
    requestBody: components["requestBodies"]["post-registration-initialize"];
    responses: {
      200: components["responses"]["post-registration-initialize"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Finish MFA Registration
   * @description Finish credential registration process
   */
  "post-mfa-registration-finalize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        /** @description Tenant ID */
        tenant_id: string;
      };
    };
    requestBody: components["requestBodies"]["post-registration-finalize"];
    responses: {
      200: components["responses"]["token"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Start MFA Login
   * @description Initialize a login flow for MFA
   */
  "post-mfa-login-initialize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        /** @description Tenant ID */
        tenant_id: string;
      };
    };
    requestBody: components["requestBodies"]["post-mfa-login-initialize"];
    responses: {
      200: components["responses"]["post-login-initialize"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
  /**
   * Finish MFA Login
   * @description Finalize the login operation
   */
  "post-mfa-login-finalize": {
    parameters: {
      header: {
        apiKey: components["parameters"]["X-API-KEY"];
      };
      path: {
        /** @description Tenant ID */
        tenant_id: string;
      };
    };
    requestBody: components["requestBodies"]["post-login-finalize"];
    responses: {
      200: components["responses"]["token"];
      400: components["responses"]["error"];
      401: components["responses"]["error"];
      404: components["responses"]["error"];
      500: components["responses"]["error"];
    };
  };
}
