name = "passkey_server_client"
version = "1.0.0"
target = "erlang"
description = "Gleam SDK for a Hanko Passkey Server (WebAuthn registration and login flows)"
licences = ["AGPL-3.0"]
repository = { type = "github", user = "ausa-social", repo = "passkeys" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 2.0.0 and < 4.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
